select * from customer;
-- Q1 What is the total revenue generated by male vs female customers
select gender as Gender,sum(purchase_amount) as Total_Revenue 
from customer 
group by gender
-- Q2 Which Customers used a discount but still spent more than average purchase amount?
select customer_id,purchase_amount 
from customer
where discount_applied='Yes' 
and purchase_amount>(select avg(purchase_amount) from customer)
-- Q3 Which are the top 5 products with the highest average review rating?
select top 5 item_purchased,round(avg(review_rating),2) as Average_Review_Rating 
from customer
group by item_purchased
order by avg(review_rating) desc;

-- Q4 Compare the average purchase amount between standard and express shipping
select shipping_type as Shipping_Type,avg(purchase_amount) as Average_Purchase_Amount
from customer
where shipping_type='Express' or shipping_type='Standard'
group by shipping_type
-- Q5 Do subscribed customers spends more? Compare average spend and total revenue between subscribers and non-subscribers
select subscription_status,
COUNT(customer_id) as total_customers,
avg(purchase_amount) as Average_Purchase_Amount,
Sum(purchase_amount) as Total_Revenue
from customer
group by subscription_status
order by Total_Revenue,Average_Purchase_Amount desc
-- Q6 Which 5 producuts have the highest percentage of purchases with discounts applied

/*
The below query is wrong because the order in which sql executes is from then where so all the rows with No as discount price will be removed
select item_purchased,count(customer_id) as Purchases
from customer
where discount_applied='Yes'
group by item_purchased
order by Purchases desc
*/
SELECT TOP 5 item_purchased, 
ROUND( 100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2 ) AS discount_rate FROM customer 
GROUP BY item_purchased
ORDER BY discount_rate DESC;
-- Q7 Segment customers into New, Returning, And Loyal Based on their total number of previous purchases
with customer_type as(
select customer_id,previous_purchases,
CASE
   when previous_purchases=1 THEN 'New'
   when previous_purchases BETWEEN 2 and 10 THEN 'Returning'
   ELSE 'Loyal'
   END AS customer_segment
from customer
)
select customer_segment,count(*) as Number_of_Customers
from customer_type
group by customer_segment
order by Number_of_Customers desc
-- Q8 What are the top 3 most purchases product within each category
with item_counts as(
select category,item_purchased,
count(customer_id) as total_order,
ROW_NUMBER() over(partition by category order by count(customer_id) desc) as item_rank
from customer 
group by category,item_purchased
)
select item_rank,category,item_purchased,total_order
from item_counts
where item_rank<=3;

--Q9 Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(*) as repeat_buyers
from customer
where previous_purchases>5
group by subscription_status

--Q10 what is the revenue contribution of each age group
select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;
